name: lib-jpeg-turbo

on:
  push:
    branches:
      - main
      - development
  pull_request:
    branches:
      - main
      - development

jobs:
  test-libjpegturbo:
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
        go: [ "1.20", "1.21" ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go }}

      - name: Set up libturbojpeg library (Linux)
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt install libturbojpeg libturbojpeg-dev

      - name: Set up jpeg-turbo library (MacOS)
        if: matrix.os == 'macos-latest'
        run: |
          brew install jpeg-turbo

      - name: Set up jpeg-turbo library (Windows)
        if: matrix.os == 'windows-latest'
        run: |
          curl -L https://master.dl.sourceforge.net/project/libjpeg-turbo/3.0.0/libjpeg-turbo-3.0.0-gcc64.exe -o libjpeg-turbo-3.0.0-gcc64.exe
          ./libjpeg-turbo-3.0.0-gcc64.exe /S

      - uses: GuillaumeFalourd/wait-sleep-action@v1
        name: Wait for jpeg-turbo silent install (Windows)
        if: matrix.os == 'windows-latest'
        with:
          time: '120'

      - name: Test package (non-Windows)
        if: matrix.os != 'windows-latest'
        run: |
          go test ./internal/image/image_jpeg -tags pdfium_use_turbojpeg -v

      - name: Test package (Windows)
        if: matrix.os == 'windows-latest'
        run: |
          $env:PKG_CONFIG_PATH = 'C:\libjpeg-turbo-gcc64\lib\pkgconfig'
          go test ./internal/image/image_jpeg -tags pdfium_use_turbojpeg -v
